mysite/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.new, name="new"),
    path('create/', views.create, name="create"),
    path('introduce/', views.introduce, name="introduce"),
    path('<int:article_pk>/', views.detail, name="detail"),
    path('<int:article_pk>/delete/', views.delete, name="delete"),
    path('<int:article_pk>/edit/', views.edit, name="edit"),
    path('<int:article_pk>/update/', views.update, name="update"),
]

mysite/jobs/urls.py
from django.urls import path
from . import views

app_name = "jobs"

urlpatterns = [
    path('', views.index, name="index"),
    path('past_life/', views.past_life, name="past_life"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('jobs/', include('jobs.urls')),
    path('movies/', include('movies.urls')),
]

mysite/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model): 
    # articles_article
    title = models.CharField(max_length=150)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}번째글 - {self.title} : {self.content}'

mysite/articles/views.py
from django.shortcuts import render, redirect
# 모델 가져오기
from .models import Article
# Create your views here.
def index(request):
    # 전체 데이터 가져오기
    articles = Article.objects.all()
    # 그 데이터 템플릿에게 넘겨주기
    context = {
        'articles' : articles
    }
    # 템플릿에서 반복분으로 각각의 게시글의
    # pk, title 보여주기
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    # 데이터 생성을 위한 ORM 활용
    # 첫번째 방법
    # article = Article()
    # article.title = title
    # article.content = content
    # article.save()

    # 두번째 방법
    # article = Article(title=title, content=content)
    # article.save()

    Article.objects.create(title=title, content=content)
    # context = {
    #     'title' : title,
    #     'content' : content
    # }
    return redirect('articles:index')

# 1. 상세페이지를 보기위한 경로
# 1-1. 특정 게시글에 대한 고유 값
# 1-2. /articles/1/, /articles/2/
# /articles/{{ article.pk }}/
# {% url 'articles:detail' article.pk %}
# 2. 해당 게시글에 대한 상세 내용
# 2-1. 게시글의 pk, title, ...
# 3. 인덱스 페이지로 돌아가는 링크
def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article' : article,
    }
    return render(request, 'articles/detail.html', context)


# 1. 특정 글 삭제를 위한 경로 작성
# 1-1. /articles/1/delete/
# 2. 글 삭제 처리를 해주는 view 작성
# 3. 글 삭제 후, index page로 redirect
# 4. 글 삭제를 위한 링크 detail에 작성
def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == "POST":
        article.delete()
        return redirect('articles:index')
    return redirect('articles:detail', article.pk)

# edit
# 1. 특정 글 수정을 위한 경로 생성
# 1-1. /articles/1/edit/
# 2. 글 수정 template을 render하는 edit view 작성
# 2-1. 해당 template에 form tag 작성
# 2-2. 각 input tag 내부에 기존 내용이 들어있어야 함.
# 2-3. value 속성을 활용

# update
# 3. edit 보낸 데이터처리를 위한 경로 생성
# 3-1. /articles/1/update/
# 4. 글 수정 처리를 하는 update view 작성
# 5. 해당 글 상세 페이지로 redirect
# 5-1. redirect('app_name:path_name', article.pk)
# 6. 글 수정을 위한 edit 링크 해당 글 상세 페이지에 생성
# 6-1. {% url 'articles:edit' article.pk %}
def edit(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article' : article,
    }
    return render(request, 'articles/edit.html', context)

def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:detail', article_pk)


# 1. /introduce/
# 2. h1 태그로 이루어진 제목
# 2-1. 각각의 p 태그에 이름과 나이 작성
# 3. back 링크로 index로 돌아갈 수 있는 링크 하나
# 4. index에서 introduce 이동할 수 있는 링크 하나
# 5. base.html 상속받아서 block body 안에 작성
def introduce(request):
    return render(request, 'articles/introduce.html')

mysite/articles/templates/articles/create.html
{% extends 'base.html' %}
{% block body %}
<h1>글 작성 완료</h1>
<hr>
<h2>제목은 {{ title }}</h2>
<p>본문은 {{ content }}</p>
<hr>
<a href="{% url 'articles:index' %}">back</a>
{% endblock %}

mysite/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block body %}
  <h1>상세 페이지</h1>
  <hr>
  <h3>{{ article.pk }}번째 글</h3>
  <p>제목 : {{ article.title }}</p>
  <p>내용 : {{ article.content }}</p>
  <p>생성 시간 : {{ article.created_at }}</p>
  <p>수정 시간 : {{ article.updated_at }}</p>
  <a href="{% url 'articles:index' %}">[back]</a>
  <a href="{% url 'articles:edit' article.pk %}">[EDIT]</a>
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="[DELETE]">
  </form>
{% endblock %}

mysite/articles/templates/articles/edit.html
{% extends 'base.html' %}
{% block body %}
<h1>수정 페이지</h1>
<form action="{% url 'articles:update' article.pk %}" method="GET">
  <h3>{{ article.pk }}번째 글</h3>
  <p>제목 : <input type="text" value="{{ article.title }}" name="title"></p>
  <label for="cnt">내용 : </label>
  <textarea name="content" id="cnt" cols="30" rows="10">{{ article.content }}</textarea>
  <input type="submit" value="수정">
</form>
{% endblock %}

mysite/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block body %}
  <h1>게시판</h1>
  <hr>
  <a href="{% url 'articles:new' %}">NEW</a>
  <br>
  <a href="{% url 'articles:introduce' %}">INTRODUCE</a>
  <hr>
  <ul>
    {% for article in articles %}
    <li><a href="{% url 'articles:detail' article.pk %}">글 번호 : {{ article.pk }} - title : {{ article.title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

mysite/articles/templates/articles/introduce.html
{% extends 'base.html' %}
{% block body %}
<h1>introduce 페이지</h1>
<hr>
<p>이름 : <input type="text"></p>
<p>나이 : <input type="text"></p>
<hr>
<a href="{% url 'articles:index' %}">back</a>
{% endblock %}

mysite/articles/templates/articles/new.html
{% extends 'base.html' %}
{% block body %}
<h1>글 작성 페이지</h1>
<hr>
<form action="{% url 'articles:create' %}" method="POST">
  {% csrf_token %}
  <label for="name">제목 : </label>
  <input type="text" id="name" name="title" placeholder="여기에 제목을 입력해 주세요.">

  <label for="cnt">내용 : </label>
  <textarea name="content" id="cnt" cols="30" rows="10">
    여기에 내용을 입력해 주세요.
  </textarea>

  <input type="submit" value="글 작성">
</form>
{% endblock %}