mysite/jobs/urls.py
from django.urls import path
from . import views

app_name = "jobs"

urlpatterns = [
    path('', views.index, name="index"),
    path('past_life/', views.past_life, name="past_life"),
]

mysite/movies/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns = [
    path('', views.movies, name="movies"),
    path('create/', views.create, name="create"),
    path('<int:movie_pk>/', views.detail, name="detail"),
    path('<int:movie_pk>/update/', views.update, name="update"),
    path('<int:movie_pk>/delete/', views.delete, name="delete"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('jobs/', include('jobs.urls')),
    path('movies/', include('movies.urls')),
]

mysite/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=150)
    title_en = models.CharField(max_length=150)
    audience = models.IntegerField(null=True)
    open_date = models.DateField()
    genre = models.CharField(max_length=150)
    watch_grade = models.CharField(max_length=150)
    score = models.FloatField(null=True)
    poster_url = models.TextField(null=True)
    description = models.TextField(null=True)

mysite/movies/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['title', 'title_en', 'audience', 'open_date', 'genre', 'watch_grade', 'score', 'poster_url', 'description']

mysite/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import MovieForm
from .models import Movie

# Create your views here.
def movies(request):
    movies = Movie.objects.all()
    context = {
        'movies' : movies
    }
    return render(request, 'movies/movies.html', context)

def create(request):
    if request.method == "POST":
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:movies')
    else:
        form = MovieForm()
    context = {
        'form' : form
    }
    return render(request, 'movies/form.html', context)

def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    context = {
        'movie' : movie
    }
    return render(request, 'movies/detail.html', context)

def update(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method == "POST":
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'form' : form
    }
    return render(request, 'movies/form.html', context)

def delete(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == "POST":
        movie.delete()
        return redirect('movies:movies')
    return redirect('movies:movies', movie.pk)

mysite/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<h1>영화 상세 정보</h1>
<hr>
{{ movie.title }}
<br>
{{ movie.title_en }}
<br>
{{ movie.audience }}
<br>
{{ movie.open_date }}
<br>
{{ movie.genre }}
<br>
{{ movie.watch_grade }}
<br>
{{ movie.score }}
<br>
<img src="{{ movie.poster_url }}" alt="" width="200" height="200">
<br>
{{ movie.description }}
<br>
<a href="{% url 'movies:movies' %}">목록</a>
<a href="{% url 'movies:update' movie.pk %}">수정</a>
<form action="{% url 'movies:delete' movie.pk %}" method="POST">
  {% csrf_token %}
  <input type="submit" value="삭제">
</form>
{% endblock %}

mysite/movies/templates/movies/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

{% if request.resolver_match.url_name == 'create' %}
  <h1>글 생성</h1>
{% else %}
  <h1>글 수정</h1>
{% endif %}
<hr>
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}
</form>
<a href="{% url 'movies:movies' %}">[BACK]</a>
{% endblock %}

mysite/movies/templates/movies/movies.html
{% extends 'base.html' %}
{% block body %}
<h1>영화 메인</h1>
<hr>
<a href="{% url 'movies:create' %}">영화 등록</a>
<hr>
<p>영화 목록</p>
{% for movie in movies %}
  <a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a>
  <br>
  <img src="{{ movie.poster_url }}" alt="" width="200" height="200">
  <br>
  {{ movie.score }}
  <hr>
{% endfor %}
{% endblock %}